// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interpretation-common.proto

package com.nuance.rpc.nlu.v1;

/**
 * <pre>
 **
 * Range of time in the input audio. Included in
 * [OperatorNode](#operatornode), [IntentNode](#intentnode),
 * [EntityNode](#entitynode), and
 * [SingleIntentEntity](#singleintententity).  Available only when
 * interpreting a recognition result from ASR as a Service.
 * </pre>
 *
 * Protobuf type {@code nuance.nlu.v1.AudioRange}
 */
public  final class AudioRange extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nuance.nlu.v1.AudioRange)
    AudioRangeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AudioRange.newBuilder() to construct.
  private AudioRange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AudioRange() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AudioRange();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AudioRange(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            startTimeMs_ = input.readUInt32();
            break;
          }
          case 16: {

            endTimeMs_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nuance.rpc.nlu.v1.InterpretationCommonProto.internal_static_nuance_nlu_v1_AudioRange_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nuance.rpc.nlu.v1.InterpretationCommonProto.internal_static_nuance_nlu_v1_AudioRange_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nuance.rpc.nlu.v1.AudioRange.class, com.nuance.rpc.nlu.v1.AudioRange.Builder.class);
  }

  public static final int START_TIME_MS_FIELD_NUMBER = 1;
  private int startTimeMs_;
  /**
   * <pre>
   * Inclusive start time in milliseconds.
   * </pre>
   *
   * <code>uint32 start_time_ms = 1;</code>
   * @return The startTimeMs.
   */
  public int getStartTimeMs() {
    return startTimeMs_;
  }

  public static final int END_TIME_MS_FIELD_NUMBER = 2;
  private int endTimeMs_;
  /**
   * <pre>
   * Exclusive end time in milliseconds.
   * </pre>
   *
   * <code>uint32 end_time_ms = 2;</code>
   * @return The endTimeMs.
   */
  public int getEndTimeMs() {
    return endTimeMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startTimeMs_ != 0) {
      output.writeUInt32(1, startTimeMs_);
    }
    if (endTimeMs_ != 0) {
      output.writeUInt32(2, endTimeMs_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startTimeMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, startTimeMs_);
    }
    if (endTimeMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, endTimeMs_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nuance.rpc.nlu.v1.AudioRange)) {
      return super.equals(obj);
    }
    com.nuance.rpc.nlu.v1.AudioRange other = (com.nuance.rpc.nlu.v1.AudioRange) obj;

    if (getStartTimeMs()
        != other.getStartTimeMs()) return false;
    if (getEndTimeMs()
        != other.getEndTimeMs()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + START_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + getStartTimeMs();
    hash = (37 * hash) + END_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + getEndTimeMs();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.AudioRange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nuance.rpc.nlu.v1.AudioRange prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Range of time in the input audio. Included in
   * [OperatorNode](#operatornode), [IntentNode](#intentnode),
   * [EntityNode](#entitynode), and
   * [SingleIntentEntity](#singleintententity).  Available only when
   * interpreting a recognition result from ASR as a Service.
   * </pre>
   *
   * Protobuf type {@code nuance.nlu.v1.AudioRange}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nuance.nlu.v1.AudioRange)
      com.nuance.rpc.nlu.v1.AudioRangeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nuance.rpc.nlu.v1.InterpretationCommonProto.internal_static_nuance_nlu_v1_AudioRange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nuance.rpc.nlu.v1.InterpretationCommonProto.internal_static_nuance_nlu_v1_AudioRange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nuance.rpc.nlu.v1.AudioRange.class, com.nuance.rpc.nlu.v1.AudioRange.Builder.class);
    }

    // Construct using com.nuance.rpc.nlu.v1.AudioRange.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      startTimeMs_ = 0;

      endTimeMs_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nuance.rpc.nlu.v1.InterpretationCommonProto.internal_static_nuance_nlu_v1_AudioRange_descriptor;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.AudioRange getDefaultInstanceForType() {
      return com.nuance.rpc.nlu.v1.AudioRange.getDefaultInstance();
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.AudioRange build() {
      com.nuance.rpc.nlu.v1.AudioRange result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.AudioRange buildPartial() {
      com.nuance.rpc.nlu.v1.AudioRange result = new com.nuance.rpc.nlu.v1.AudioRange(this);
      result.startTimeMs_ = startTimeMs_;
      result.endTimeMs_ = endTimeMs_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nuance.rpc.nlu.v1.AudioRange) {
        return mergeFrom((com.nuance.rpc.nlu.v1.AudioRange)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nuance.rpc.nlu.v1.AudioRange other) {
      if (other == com.nuance.rpc.nlu.v1.AudioRange.getDefaultInstance()) return this;
      if (other.getStartTimeMs() != 0) {
        setStartTimeMs(other.getStartTimeMs());
      }
      if (other.getEndTimeMs() != 0) {
        setEndTimeMs(other.getEndTimeMs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nuance.rpc.nlu.v1.AudioRange parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nuance.rpc.nlu.v1.AudioRange) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int startTimeMs_ ;
    /**
     * <pre>
     * Inclusive start time in milliseconds.
     * </pre>
     *
     * <code>uint32 start_time_ms = 1;</code>
     * @return The startTimeMs.
     */
    public int getStartTimeMs() {
      return startTimeMs_;
    }
    /**
     * <pre>
     * Inclusive start time in milliseconds.
     * </pre>
     *
     * <code>uint32 start_time_ms = 1;</code>
     * @param value The startTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setStartTimeMs(int value) {
      
      startTimeMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Inclusive start time in milliseconds.
     * </pre>
     *
     * <code>uint32 start_time_ms = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTimeMs() {
      
      startTimeMs_ = 0;
      onChanged();
      return this;
    }

    private int endTimeMs_ ;
    /**
     * <pre>
     * Exclusive end time in milliseconds.
     * </pre>
     *
     * <code>uint32 end_time_ms = 2;</code>
     * @return The endTimeMs.
     */
    public int getEndTimeMs() {
      return endTimeMs_;
    }
    /**
     * <pre>
     * Exclusive end time in milliseconds.
     * </pre>
     *
     * <code>uint32 end_time_ms = 2;</code>
     * @param value The endTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setEndTimeMs(int value) {
      
      endTimeMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Exclusive end time in milliseconds.
     * </pre>
     *
     * <code>uint32 end_time_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTimeMs() {
      
      endTimeMs_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nuance.nlu.v1.AudioRange)
  }

  // @@protoc_insertion_point(class_scope:nuance.nlu.v1.AudioRange)
  private static final com.nuance.rpc.nlu.v1.AudioRange DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nuance.rpc.nlu.v1.AudioRange();
  }

  public static com.nuance.rpc.nlu.v1.AudioRange getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AudioRange>
      PARSER = new com.google.protobuf.AbstractParser<AudioRange>() {
    @java.lang.Override
    public AudioRange parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AudioRange(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AudioRange> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AudioRange> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nuance.rpc.nlu.v1.AudioRange getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

