// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime.proto

package com.nuance.rpc.nlu.v1;

/**
 * <pre>
 **
 * Format for input in the diagnostic logs.  Included in
 * [InterpretationParameters](#interpretationparameters).
 * </pre>
 *
 * Protobuf enum {@code nuance.nlu.v1.EnumInterpretationInputLoggingMode}
 */
public enum EnumInterpretationInputLoggingMode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default. Log the literal text of the input.
   * </pre>
   *
   * <code>PLAINTEXT = 0;</code>
   */
  PLAINTEXT(0),
  /**
   * <pre>
   * Input is replaced with "value suppressed."
   * </pre>
   *
   * <code>SUPPRESSED = 9;</code>
   */
  SUPPRESSED(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Default. Log the literal text of the input.
   * </pre>
   *
   * <code>PLAINTEXT = 0;</code>
   */
  public static final int PLAINTEXT_VALUE = 0;
  /**
   * <pre>
   * Input is replaced with "value suppressed."
   * </pre>
   *
   * <code>SUPPRESSED = 9;</code>
   */
  public static final int SUPPRESSED_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EnumInterpretationInputLoggingMode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EnumInterpretationInputLoggingMode forNumber(int value) {
    switch (value) {
      case 0: return PLAINTEXT;
      case 9: return SUPPRESSED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EnumInterpretationInputLoggingMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EnumInterpretationInputLoggingMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EnumInterpretationInputLoggingMode>() {
          public EnumInterpretationInputLoggingMode findValueByNumber(int number) {
            return EnumInterpretationInputLoggingMode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.nuance.rpc.nlu.v1.RuntimeProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final EnumInterpretationInputLoggingMode[] VALUES = values();

  public static EnumInterpretationInputLoggingMode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EnumInterpretationInputLoggingMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nuance.nlu.v1.EnumInterpretationInputLoggingMode)
}

