// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multi-intent-interpretation.proto

package com.nuance.rpc.nlu.v1;

/**
 * <pre>
 **
 * Logical operator type, AND, OR, or NOT. Included in [OperatorNode](#operatornode).
 * </pre>
 *
 * Protobuf enum {@code nuance.nlu.v1.EnumOperator}
 */
public enum EnumOperator
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * The following item is an additional intent or entity. 
   * </pre>
   *
   * <code>AND = 0;</code>
   */
  AND(0),
  /**
   * <pre>
   * The following item is an alternative intent or entity.
   * </pre>
   *
   * <code>OR = 1;</code>
   */
  OR(1),
  /**
   * <pre>
   * The following item is not detected.
   * </pre>
   *
   * <code>NOT = 2;</code>
   */
  NOT(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * The following item is an additional intent or entity. 
   * </pre>
   *
   * <code>AND = 0;</code>
   */
  public static final int AND_VALUE = 0;
  /**
   * <pre>
   * The following item is an alternative intent or entity.
   * </pre>
   *
   * <code>OR = 1;</code>
   */
  public static final int OR_VALUE = 1;
  /**
   * <pre>
   * The following item is not detected.
   * </pre>
   *
   * <code>NOT = 2;</code>
   */
  public static final int NOT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EnumOperator valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EnumOperator forNumber(int value) {
    switch (value) {
      case 0: return AND;
      case 1: return OR;
      case 2: return NOT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EnumOperator>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EnumOperator> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EnumOperator>() {
          public EnumOperator findValueByNumber(int number) {
            return EnumOperator.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.nuance.rpc.nlu.v1.MultiIntentInterpretationProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final EnumOperator[] VALUES = values();

  public static EnumOperator valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EnumOperator(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nuance.nlu.v1.EnumOperator)
}

