// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime.proto

package com.nuance.rpc.nlu.v1;

/**
 * <pre>
 **
 * Format of interpretations result.  Included in
 * [InterpretationParameters](#interpretationparameters).
 * </pre>
 *
 * Protobuf enum {@code nuance.nlu.v1.EnumInterpretationResultType}
 */
public enum EnumInterpretationResultType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default. Same as SINGLE_INTENT.
   * </pre>
   *
   * <code>UNDEFINED = 0;</code>
   */
  UNDEFINED(0),
  /**
   * <pre>
   * Always return a single-intent interpretation.
   * </pre>
   *
   * <code>SINGLE_INTENT = 1;</code>
   */
  SINGLE_INTENT(1),
  /**
   * <pre>
   * Always return multi-intent interpretation.
   * </pre>
   *
   * <code>MULTI_INTENT = 2;</code>
   */
  MULTI_INTENT(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Default. Same as SINGLE_INTENT.
   * </pre>
   *
   * <code>UNDEFINED = 0;</code>
   */
  public static final int UNDEFINED_VALUE = 0;
  /**
   * <pre>
   * Always return a single-intent interpretation.
   * </pre>
   *
   * <code>SINGLE_INTENT = 1;</code>
   */
  public static final int SINGLE_INTENT_VALUE = 1;
  /**
   * <pre>
   * Always return multi-intent interpretation.
   * </pre>
   *
   * <code>MULTI_INTENT = 2;</code>
   */
  public static final int MULTI_INTENT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EnumInterpretationResultType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EnumInterpretationResultType forNumber(int value) {
    switch (value) {
      case 0: return UNDEFINED;
      case 1: return SINGLE_INTENT;
      case 2: return MULTI_INTENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EnumInterpretationResultType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EnumInterpretationResultType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EnumInterpretationResultType>() {
          public EnumInterpretationResultType findValueByNumber(int number) {
            return EnumInterpretationResultType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.nuance.rpc.nlu.v1.RuntimeProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final EnumInterpretationResultType[] VALUES = values();

  public static EnumInterpretationResultType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EnumInterpretationResultType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nuance.nlu.v1.EnumInterpretationResultType)
}

