// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime.proto

package com.nuance.rpc.nlu.v1;

public interface InterpretationResourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nuance.nlu.v1.InterpretationResource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * External resource.
   * </pre>
   *
   * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
   * @return Whether the externalReference field is set.
   */
  boolean hasExternalReference();
  /**
   * <pre>
   * External resource.
   * </pre>
   *
   * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
   * @return The externalReference.
   */
  com.nuance.rpc.nlu.v1.ResourceReference getExternalReference();
  /**
   * <pre>
   * External resource.
   * </pre>
   *
   * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
   */
  com.nuance.rpc.nlu.v1.ResourceReferenceOrBuilder getExternalReferenceOrBuilder();

  /**
   * <pre>
   * Inline wordset, in JSON.
   * </pre>
   *
   * <code>string inline_wordset = 2;</code>
   * @return The inlineWordset.
   */
  java.lang.String getInlineWordset();
  /**
   * <pre>
   * Inline wordset, in JSON.
   * </pre>
   *
   * <code>string inline_wordset = 2;</code>
   * @return The bytes for inlineWordset.
   */
  com.google.protobuf.ByteString
      getInlineWordsetBytes();

  public com.nuance.rpc.nlu.v1.InterpretationResource.ResourceUnionCase getResourceUnionCase();
}
