// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime.proto

package com.nuance.rpc.nlu.v1;

/**
 * <pre>
 **
 * The interpretation result. Included in the [Nlu](#nlu) service.
 * </pre>
 *
 * Protobuf type {@code nuance.nlu.v1.InterpretResponse}
 */
public  final class InterpretResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nuance.nlu.v1.InterpretResponse)
    InterpretResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InterpretResponse.newBuilder() to construct.
  private InterpretResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InterpretResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InterpretResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InterpretResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.nuance.rpc.nlu.v1.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(com.nuance.rpc.nlu.v1.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.nuance.rpc.nlu.v1.InterpretResult.Builder subBuilder = null;
            if (result_ != null) {
              subBuilder = result_.toBuilder();
            }
            result_ = input.readMessage(com.nuance.rpc.nlu.v1.InterpretResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(result_);
              result_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nuance.rpc.nlu.v1.InterpretResponse.class, com.nuance.rpc.nlu.v1.InterpretResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private com.nuance.rpc.nlu.v1.Status status_;
  /**
   * <pre>
   * Whether the request was successful. The 200 code means success, other values indicate an error.
   * </pre>
   *
   * <code>.nuance.nlu.v1.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <pre>
   * Whether the request was successful. The 200 code means success, other values indicate an error.
   * </pre>
   *
   * <code>.nuance.nlu.v1.Status status = 1;</code>
   * @return The status.
   */
  public com.nuance.rpc.nlu.v1.Status getStatus() {
    return status_ == null ? com.nuance.rpc.nlu.v1.Status.getDefaultInstance() : status_;
  }
  /**
   * <pre>
   * Whether the request was successful. The 200 code means success, other values indicate an error.
   * </pre>
   *
   * <code>.nuance.nlu.v1.Status status = 1;</code>
   */
  public com.nuance.rpc.nlu.v1.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int RESULT_FIELD_NUMBER = 3;
  private com.nuance.rpc.nlu.v1.InterpretResult result_;
  /**
   * <pre>
   * The result of the interpretation.
   * </pre>
   *
   * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
   * @return Whether the result field is set.
   */
  public boolean hasResult() {
    return result_ != null;
  }
  /**
   * <pre>
   * The result of the interpretation.
   * </pre>
   *
   * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
   * @return The result.
   */
  public com.nuance.rpc.nlu.v1.InterpretResult getResult() {
    return result_ == null ? com.nuance.rpc.nlu.v1.InterpretResult.getDefaultInstance() : result_;
  }
  /**
   * <pre>
   * The result of the interpretation.
   * </pre>
   *
   * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
   */
  public com.nuance.rpc.nlu.v1.InterpretResultOrBuilder getResultOrBuilder() {
    return getResult();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != null) {
      output.writeMessage(1, getStatus());
    }
    if (result_ != null) {
      output.writeMessage(3, getResult());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (result_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getResult());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nuance.rpc.nlu.v1.InterpretResponse)) {
      return super.equals(obj);
    }
    com.nuance.rpc.nlu.v1.InterpretResponse other = (com.nuance.rpc.nlu.v1.InterpretResponse) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasResult() != other.hasResult()) return false;
    if (hasResult()) {
      if (!getResult()
          .equals(other.getResult())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasResult()) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.InterpretResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nuance.rpc.nlu.v1.InterpretResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * The interpretation result. Included in the [Nlu](#nlu) service.
   * </pre>
   *
   * Protobuf type {@code nuance.nlu.v1.InterpretResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nuance.nlu.v1.InterpretResponse)
      com.nuance.rpc.nlu.v1.InterpretResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nuance.rpc.nlu.v1.InterpretResponse.class, com.nuance.rpc.nlu.v1.InterpretResponse.Builder.class);
    }

    // Construct using com.nuance.rpc.nlu.v1.InterpretResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      if (resultBuilder_ == null) {
        result_ = null;
      } else {
        result_ = null;
        resultBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretResponse_descriptor;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.InterpretResponse getDefaultInstanceForType() {
      return com.nuance.rpc.nlu.v1.InterpretResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.InterpretResponse build() {
      com.nuance.rpc.nlu.v1.InterpretResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.InterpretResponse buildPartial() {
      com.nuance.rpc.nlu.v1.InterpretResponse result = new com.nuance.rpc.nlu.v1.InterpretResponse(this);
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (resultBuilder_ == null) {
        result.result_ = result_;
      } else {
        result.result_ = resultBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nuance.rpc.nlu.v1.InterpretResponse) {
        return mergeFrom((com.nuance.rpc.nlu.v1.InterpretResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nuance.rpc.nlu.v1.InterpretResponse other) {
      if (other == com.nuance.rpc.nlu.v1.InterpretResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasResult()) {
        mergeResult(other.getResult());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nuance.rpc.nlu.v1.InterpretResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nuance.rpc.nlu.v1.InterpretResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.nuance.rpc.nlu.v1.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.Status, com.nuance.rpc.nlu.v1.Status.Builder, com.nuance.rpc.nlu.v1.StatusOrBuilder> statusBuilder_;
    /**
     * <pre>
     * Whether the request was successful. The 200 code means success, other values indicate an error.
     * </pre>
     *
     * <code>.nuance.nlu.v1.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <pre>
     * Whether the request was successful. The 200 code means success, other values indicate an error.
     * </pre>
     *
     * <code>.nuance.nlu.v1.Status status = 1;</code>
     * @return The status.
     */
    public com.nuance.rpc.nlu.v1.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.nuance.rpc.nlu.v1.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Whether the request was successful. The 200 code means success, other values indicate an error.
     * </pre>
     *
     * <code>.nuance.nlu.v1.Status status = 1;</code>
     */
    public Builder setStatus(com.nuance.rpc.nlu.v1.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Whether the request was successful. The 200 code means success, other values indicate an error.
     * </pre>
     *
     * <code>.nuance.nlu.v1.Status status = 1;</code>
     */
    public Builder setStatus(
        com.nuance.rpc.nlu.v1.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Whether the request was successful. The 200 code means success, other values indicate an error.
     * </pre>
     *
     * <code>.nuance.nlu.v1.Status status = 1;</code>
     */
    public Builder mergeStatus(com.nuance.rpc.nlu.v1.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            com.nuance.rpc.nlu.v1.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Whether the request was successful. The 200 code means success, other values indicate an error.
     * </pre>
     *
     * <code>.nuance.nlu.v1.Status status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Whether the request was successful. The 200 code means success, other values indicate an error.
     * </pre>
     *
     * <code>.nuance.nlu.v1.Status status = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Whether the request was successful. The 200 code means success, other values indicate an error.
     * </pre>
     *
     * <code>.nuance.nlu.v1.Status status = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.nuance.rpc.nlu.v1.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <pre>
     * Whether the request was successful. The 200 code means success, other values indicate an error.
     * </pre>
     *
     * <code>.nuance.nlu.v1.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.Status, com.nuance.rpc.nlu.v1.Status.Builder, com.nuance.rpc.nlu.v1.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.nuance.rpc.nlu.v1.Status, com.nuance.rpc.nlu.v1.Status.Builder, com.nuance.rpc.nlu.v1.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private com.nuance.rpc.nlu.v1.InterpretResult result_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.InterpretResult, com.nuance.rpc.nlu.v1.InterpretResult.Builder, com.nuance.rpc.nlu.v1.InterpretResultOrBuilder> resultBuilder_;
    /**
     * <pre>
     * The result of the interpretation.
     * </pre>
     *
     * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
     * @return Whether the result field is set.
     */
    public boolean hasResult() {
      return resultBuilder_ != null || result_ != null;
    }
    /**
     * <pre>
     * The result of the interpretation.
     * </pre>
     *
     * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
     * @return The result.
     */
    public com.nuance.rpc.nlu.v1.InterpretResult getResult() {
      if (resultBuilder_ == null) {
        return result_ == null ? com.nuance.rpc.nlu.v1.InterpretResult.getDefaultInstance() : result_;
      } else {
        return resultBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The result of the interpretation.
     * </pre>
     *
     * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
     */
    public Builder setResult(com.nuance.rpc.nlu.v1.InterpretResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        resultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The result of the interpretation.
     * </pre>
     *
     * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
     */
    public Builder setResult(
        com.nuance.rpc.nlu.v1.InterpretResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The result of the interpretation.
     * </pre>
     *
     * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
     */
    public Builder mergeResult(com.nuance.rpc.nlu.v1.InterpretResult value) {
      if (resultBuilder_ == null) {
        if (result_ != null) {
          result_ =
            com.nuance.rpc.nlu.v1.InterpretResult.newBuilder(result_).mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        resultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The result of the interpretation.
     * </pre>
     *
     * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        result_ = null;
        onChanged();
      } else {
        result_ = null;
        resultBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The result of the interpretation.
     * </pre>
     *
     * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
     */
    public com.nuance.rpc.nlu.v1.InterpretResult.Builder getResultBuilder() {
      
      onChanged();
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The result of the interpretation.
     * </pre>
     *
     * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
     */
    public com.nuance.rpc.nlu.v1.InterpretResultOrBuilder getResultOrBuilder() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        return result_ == null ?
            com.nuance.rpc.nlu.v1.InterpretResult.getDefaultInstance() : result_;
      }
    }
    /**
     * <pre>
     * The result of the interpretation.
     * </pre>
     *
     * <code>.nuance.nlu.v1.InterpretResult result = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.InterpretResult, com.nuance.rpc.nlu.v1.InterpretResult.Builder, com.nuance.rpc.nlu.v1.InterpretResultOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.nuance.rpc.nlu.v1.InterpretResult, com.nuance.rpc.nlu.v1.InterpretResult.Builder, com.nuance.rpc.nlu.v1.InterpretResultOrBuilder>(
                getResult(),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nuance.nlu.v1.InterpretResponse)
  }

  // @@protoc_insertion_point(class_scope:nuance.nlu.v1.InterpretResponse)
  private static final com.nuance.rpc.nlu.v1.InterpretResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nuance.rpc.nlu.v1.InterpretResponse();
  }

  public static com.nuance.rpc.nlu.v1.InterpretResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InterpretResponse>
      PARSER = new com.google.protobuf.AbstractParser<InterpretResponse>() {
    @java.lang.Override
    public InterpretResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InterpretResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InterpretResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InterpretResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nuance.rpc.nlu.v1.InterpretResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

