// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime.proto

package com.nuance.rpc.nlu.v1;

/**
 * <pre>
 **
 * Input to interpret. Included in
 * [InterpretRequest](#interpretrequest). Use either text or the
 * [result](../../asr-grpc/v1/index.html#result) from ASR as a
 * Service.
 * </pre>
 *
 * Protobuf type {@code nuance.nlu.v1.InterpretationInput}
 */
public  final class InterpretationInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nuance.nlu.v1.InterpretationInput)
    InterpretationInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InterpretationInput.newBuilder() to construct.
  private InterpretationInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InterpretationInput() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InterpretationInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InterpretationInput(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            inputUnionCase_ = 1;
            inputUnion_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (inputUnionCase_ == 2) {
              subBuilder = ((com.google.protobuf.Any) inputUnion_).toBuilder();
            }
            inputUnion_ =
                input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Any) inputUnion_);
              inputUnion_ = subBuilder.buildPartial();
            }
            inputUnionCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nuance.rpc.nlu.v1.InterpretationInput.class, com.nuance.rpc.nlu.v1.InterpretationInput.Builder.class);
  }

  private int inputUnionCase_ = 0;
  private java.lang.Object inputUnion_;
  public enum InputUnionCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TEXT(1),
    ASR_RESULT(2),
    INPUTUNION_NOT_SET(0);
    private final int value;
    private InputUnionCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InputUnionCase valueOf(int value) {
      return forNumber(value);
    }

    public static InputUnionCase forNumber(int value) {
      switch (value) {
        case 1: return TEXT;
        case 2: return ASR_RESULT;
        case 0: return INPUTUNION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public InputUnionCase
  getInputUnionCase() {
    return InputUnionCase.forNumber(
        inputUnionCase_);
  }

  public static final int TEXT_FIELD_NUMBER = 1;
  /**
   * <pre>
   * Text input.
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The text.
   */
  public java.lang.String getText() {
    java.lang.Object ref = "";
    if (inputUnionCase_ == 1) {
      ref = inputUnion_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (inputUnionCase_ == 1) {
        inputUnion_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Text input.
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = "";
    if (inputUnionCase_ == 1) {
      ref = inputUnion_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (inputUnionCase_ == 1) {
        inputUnion_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASR_RESULT_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Result from ASR as a Service.
   * </pre>
   *
   * <code>.google.protobuf.Any asr_result = 2;</code>
   * @return Whether the asrResult field is set.
   */
  public boolean hasAsrResult() {
    return inputUnionCase_ == 2;
  }
  /**
   * <pre>
   * Result from ASR as a Service.
   * </pre>
   *
   * <code>.google.protobuf.Any asr_result = 2;</code>
   * @return The asrResult.
   */
  public com.google.protobuf.Any getAsrResult() {
    if (inputUnionCase_ == 2) {
       return (com.google.protobuf.Any) inputUnion_;
    }
    return com.google.protobuf.Any.getDefaultInstance();
  }
  /**
   * <pre>
   * Result from ASR as a Service.
   * </pre>
   *
   * <code>.google.protobuf.Any asr_result = 2;</code>
   */
  public com.google.protobuf.AnyOrBuilder getAsrResultOrBuilder() {
    if (inputUnionCase_ == 2) {
       return (com.google.protobuf.Any) inputUnion_;
    }
    return com.google.protobuf.Any.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (inputUnionCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, inputUnion_);
    }
    if (inputUnionCase_ == 2) {
      output.writeMessage(2, (com.google.protobuf.Any) inputUnion_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (inputUnionCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, inputUnion_);
    }
    if (inputUnionCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.google.protobuf.Any) inputUnion_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nuance.rpc.nlu.v1.InterpretationInput)) {
      return super.equals(obj);
    }
    com.nuance.rpc.nlu.v1.InterpretationInput other = (com.nuance.rpc.nlu.v1.InterpretationInput) obj;

    if (!getInputUnionCase().equals(other.getInputUnionCase())) return false;
    switch (inputUnionCase_) {
      case 1:
        if (!getText()
            .equals(other.getText())) return false;
        break;
      case 2:
        if (!getAsrResult()
            .equals(other.getAsrResult())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (inputUnionCase_) {
      case 1:
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ASR_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getAsrResult().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nuance.rpc.nlu.v1.InterpretationInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Input to interpret. Included in
   * [InterpretRequest](#interpretrequest). Use either text or the
   * [result](../../asr-grpc/v1/index.html#result) from ASR as a
   * Service.
   * </pre>
   *
   * Protobuf type {@code nuance.nlu.v1.InterpretationInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nuance.nlu.v1.InterpretationInput)
      com.nuance.rpc.nlu.v1.InterpretationInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nuance.rpc.nlu.v1.InterpretationInput.class, com.nuance.rpc.nlu.v1.InterpretationInput.Builder.class);
    }

    // Construct using com.nuance.rpc.nlu.v1.InterpretationInput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      inputUnionCase_ = 0;
      inputUnion_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationInput_descriptor;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.InterpretationInput getDefaultInstanceForType() {
      return com.nuance.rpc.nlu.v1.InterpretationInput.getDefaultInstance();
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.InterpretationInput build() {
      com.nuance.rpc.nlu.v1.InterpretationInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.InterpretationInput buildPartial() {
      com.nuance.rpc.nlu.v1.InterpretationInput result = new com.nuance.rpc.nlu.v1.InterpretationInput(this);
      if (inputUnionCase_ == 1) {
        result.inputUnion_ = inputUnion_;
      }
      if (inputUnionCase_ == 2) {
        if (asrResultBuilder_ == null) {
          result.inputUnion_ = inputUnion_;
        } else {
          result.inputUnion_ = asrResultBuilder_.build();
        }
      }
      result.inputUnionCase_ = inputUnionCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nuance.rpc.nlu.v1.InterpretationInput) {
        return mergeFrom((com.nuance.rpc.nlu.v1.InterpretationInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nuance.rpc.nlu.v1.InterpretationInput other) {
      if (other == com.nuance.rpc.nlu.v1.InterpretationInput.getDefaultInstance()) return this;
      switch (other.getInputUnionCase()) {
        case TEXT: {
          inputUnionCase_ = 1;
          inputUnion_ = other.inputUnion_;
          onChanged();
          break;
        }
        case ASR_RESULT: {
          mergeAsrResult(other.getAsrResult());
          break;
        }
        case INPUTUNION_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nuance.rpc.nlu.v1.InterpretationInput parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nuance.rpc.nlu.v1.InterpretationInput) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int inputUnionCase_ = 0;
    private java.lang.Object inputUnion_;
    public InputUnionCase
        getInputUnionCase() {
      return InputUnionCase.forNumber(
          inputUnionCase_);
    }

    public Builder clearInputUnion() {
      inputUnionCase_ = 0;
      inputUnion_ = null;
      onChanged();
      return this;
    }


    /**
     * <pre>
     * Text input.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = "";
      if (inputUnionCase_ == 1) {
        ref = inputUnion_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (inputUnionCase_ == 1) {
          inputUnion_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Text input.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = "";
      if (inputUnionCase_ == 1) {
        ref = inputUnion_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (inputUnionCase_ == 1) {
          inputUnion_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Text input.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  inputUnionCase_ = 1;
      inputUnion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Text input.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      if (inputUnionCase_ == 1) {
        inputUnionCase_ = 0;
        inputUnion_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Text input.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      inputUnionCase_ = 1;
      inputUnion_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> asrResultBuilder_;
    /**
     * <pre>
     * Result from ASR as a Service.
     * </pre>
     *
     * <code>.google.protobuf.Any asr_result = 2;</code>
     * @return Whether the asrResult field is set.
     */
    public boolean hasAsrResult() {
      return inputUnionCase_ == 2;
    }
    /**
     * <pre>
     * Result from ASR as a Service.
     * </pre>
     *
     * <code>.google.protobuf.Any asr_result = 2;</code>
     * @return The asrResult.
     */
    public com.google.protobuf.Any getAsrResult() {
      if (asrResultBuilder_ == null) {
        if (inputUnionCase_ == 2) {
          return (com.google.protobuf.Any) inputUnion_;
        }
        return com.google.protobuf.Any.getDefaultInstance();
      } else {
        if (inputUnionCase_ == 2) {
          return asrResultBuilder_.getMessage();
        }
        return com.google.protobuf.Any.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Result from ASR as a Service.
     * </pre>
     *
     * <code>.google.protobuf.Any asr_result = 2;</code>
     */
    public Builder setAsrResult(com.google.protobuf.Any value) {
      if (asrResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inputUnion_ = value;
        onChanged();
      } else {
        asrResultBuilder_.setMessage(value);
      }
      inputUnionCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Result from ASR as a Service.
     * </pre>
     *
     * <code>.google.protobuf.Any asr_result = 2;</code>
     */
    public Builder setAsrResult(
        com.google.protobuf.Any.Builder builderForValue) {
      if (asrResultBuilder_ == null) {
        inputUnion_ = builderForValue.build();
        onChanged();
      } else {
        asrResultBuilder_.setMessage(builderForValue.build());
      }
      inputUnionCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Result from ASR as a Service.
     * </pre>
     *
     * <code>.google.protobuf.Any asr_result = 2;</code>
     */
    public Builder mergeAsrResult(com.google.protobuf.Any value) {
      if (asrResultBuilder_ == null) {
        if (inputUnionCase_ == 2 &&
            inputUnion_ != com.google.protobuf.Any.getDefaultInstance()) {
          inputUnion_ = com.google.protobuf.Any.newBuilder((com.google.protobuf.Any) inputUnion_)
              .mergeFrom(value).buildPartial();
        } else {
          inputUnion_ = value;
        }
        onChanged();
      } else {
        if (inputUnionCase_ == 2) {
          asrResultBuilder_.mergeFrom(value);
        }
        asrResultBuilder_.setMessage(value);
      }
      inputUnionCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Result from ASR as a Service.
     * </pre>
     *
     * <code>.google.protobuf.Any asr_result = 2;</code>
     */
    public Builder clearAsrResult() {
      if (asrResultBuilder_ == null) {
        if (inputUnionCase_ == 2) {
          inputUnionCase_ = 0;
          inputUnion_ = null;
          onChanged();
        }
      } else {
        if (inputUnionCase_ == 2) {
          inputUnionCase_ = 0;
          inputUnion_ = null;
        }
        asrResultBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Result from ASR as a Service.
     * </pre>
     *
     * <code>.google.protobuf.Any asr_result = 2;</code>
     */
    public com.google.protobuf.Any.Builder getAsrResultBuilder() {
      return getAsrResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Result from ASR as a Service.
     * </pre>
     *
     * <code>.google.protobuf.Any asr_result = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getAsrResultOrBuilder() {
      if ((inputUnionCase_ == 2) && (asrResultBuilder_ != null)) {
        return asrResultBuilder_.getMessageOrBuilder();
      } else {
        if (inputUnionCase_ == 2) {
          return (com.google.protobuf.Any) inputUnion_;
        }
        return com.google.protobuf.Any.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Result from ASR as a Service.
     * </pre>
     *
     * <code>.google.protobuf.Any asr_result = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getAsrResultFieldBuilder() {
      if (asrResultBuilder_ == null) {
        if (!(inputUnionCase_ == 2)) {
          inputUnion_ = com.google.protobuf.Any.getDefaultInstance();
        }
        asrResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                (com.google.protobuf.Any) inputUnion_,
                getParentForChildren(),
                isClean());
        inputUnion_ = null;
      }
      inputUnionCase_ = 2;
      onChanged();;
      return asrResultBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nuance.nlu.v1.InterpretationInput)
  }

  // @@protoc_insertion_point(class_scope:nuance.nlu.v1.InterpretationInput)
  private static final com.nuance.rpc.nlu.v1.InterpretationInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nuance.rpc.nlu.v1.InterpretationInput();
  }

  public static com.nuance.rpc.nlu.v1.InterpretationInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InterpretationInput>
      PARSER = new com.google.protobuf.AbstractParser<InterpretationInput>() {
    @java.lang.Override
    public InterpretationInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InterpretationInput(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InterpretationInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InterpretationInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nuance.rpc.nlu.v1.InterpretationInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

