// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime.proto

package com.nuance.rpc.nlu.v1;

/**
 * <pre>
 **
 * A resource to customize the interpretation. Included in
 * [InterpretRequest](#interpretrequest).
 * </pre>
 *
 * Protobuf type {@code nuance.nlu.v1.InterpretationResource}
 */
public  final class InterpretationResource extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nuance.nlu.v1.InterpretationResource)
    InterpretationResourceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InterpretationResource.newBuilder() to construct.
  private InterpretationResource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InterpretationResource() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InterpretationResource();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InterpretationResource(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.nuance.rpc.nlu.v1.ResourceReference.Builder subBuilder = null;
            if (resourceUnionCase_ == 1) {
              subBuilder = ((com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_).toBuilder();
            }
            resourceUnion_ =
                input.readMessage(com.nuance.rpc.nlu.v1.ResourceReference.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_);
              resourceUnion_ = subBuilder.buildPartial();
            }
            resourceUnionCase_ = 1;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            resourceUnionCase_ = 2;
            resourceUnion_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationResource_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationResource_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nuance.rpc.nlu.v1.InterpretationResource.class, com.nuance.rpc.nlu.v1.InterpretationResource.Builder.class);
  }

  private int resourceUnionCase_ = 0;
  private java.lang.Object resourceUnion_;
  public enum ResourceUnionCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    EXTERNAL_REFERENCE(1),
    INLINE_WORDSET(2),
    RESOURCEUNION_NOT_SET(0);
    private final int value;
    private ResourceUnionCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResourceUnionCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResourceUnionCase forNumber(int value) {
      switch (value) {
        case 1: return EXTERNAL_REFERENCE;
        case 2: return INLINE_WORDSET;
        case 0: return RESOURCEUNION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResourceUnionCase
  getResourceUnionCase() {
    return ResourceUnionCase.forNumber(
        resourceUnionCase_);
  }

  public static final int EXTERNAL_REFERENCE_FIELD_NUMBER = 1;
  /**
   * <pre>
   * External resource.
   * </pre>
   *
   * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
   * @return Whether the externalReference field is set.
   */
  public boolean hasExternalReference() {
    return resourceUnionCase_ == 1;
  }
  /**
   * <pre>
   * External resource.
   * </pre>
   *
   * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
   * @return The externalReference.
   */
  public com.nuance.rpc.nlu.v1.ResourceReference getExternalReference() {
    if (resourceUnionCase_ == 1) {
       return (com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_;
    }
    return com.nuance.rpc.nlu.v1.ResourceReference.getDefaultInstance();
  }
  /**
   * <pre>
   * External resource.
   * </pre>
   *
   * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
   */
  public com.nuance.rpc.nlu.v1.ResourceReferenceOrBuilder getExternalReferenceOrBuilder() {
    if (resourceUnionCase_ == 1) {
       return (com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_;
    }
    return com.nuance.rpc.nlu.v1.ResourceReference.getDefaultInstance();
  }

  public static final int INLINE_WORDSET_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Inline wordset, in JSON.
   * </pre>
   *
   * <code>string inline_wordset = 2;</code>
   * @return The inlineWordset.
   */
  public java.lang.String getInlineWordset() {
    java.lang.Object ref = "";
    if (resourceUnionCase_ == 2) {
      ref = resourceUnion_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (resourceUnionCase_ == 2) {
        resourceUnion_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Inline wordset, in JSON.
   * </pre>
   *
   * <code>string inline_wordset = 2;</code>
   * @return The bytes for inlineWordset.
   */
  public com.google.protobuf.ByteString
      getInlineWordsetBytes() {
    java.lang.Object ref = "";
    if (resourceUnionCase_ == 2) {
      ref = resourceUnion_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (resourceUnionCase_ == 2) {
        resourceUnion_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resourceUnionCase_ == 1) {
      output.writeMessage(1, (com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_);
    }
    if (resourceUnionCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resourceUnion_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resourceUnionCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_);
    }
    if (resourceUnionCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resourceUnion_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nuance.rpc.nlu.v1.InterpretationResource)) {
      return super.equals(obj);
    }
    com.nuance.rpc.nlu.v1.InterpretationResource other = (com.nuance.rpc.nlu.v1.InterpretationResource) obj;

    if (!getResourceUnionCase().equals(other.getResourceUnionCase())) return false;
    switch (resourceUnionCase_) {
      case 1:
        if (!getExternalReference()
            .equals(other.getExternalReference())) return false;
        break;
      case 2:
        if (!getInlineWordset()
            .equals(other.getInlineWordset())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (resourceUnionCase_) {
      case 1:
        hash = (37 * hash) + EXTERNAL_REFERENCE_FIELD_NUMBER;
        hash = (53 * hash) + getExternalReference().hashCode();
        break;
      case 2:
        hash = (37 * hash) + INLINE_WORDSET_FIELD_NUMBER;
        hash = (53 * hash) + getInlineWordset().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.InterpretationResource parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nuance.rpc.nlu.v1.InterpretationResource prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * A resource to customize the interpretation. Included in
   * [InterpretRequest](#interpretrequest).
   * </pre>
   *
   * Protobuf type {@code nuance.nlu.v1.InterpretationResource}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nuance.nlu.v1.InterpretationResource)
      com.nuance.rpc.nlu.v1.InterpretationResourceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationResource_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationResource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nuance.rpc.nlu.v1.InterpretationResource.class, com.nuance.rpc.nlu.v1.InterpretationResource.Builder.class);
    }

    // Construct using com.nuance.rpc.nlu.v1.InterpretationResource.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      resourceUnionCase_ = 0;
      resourceUnion_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nuance.rpc.nlu.v1.RuntimeProto.internal_static_nuance_nlu_v1_InterpretationResource_descriptor;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.InterpretationResource getDefaultInstanceForType() {
      return com.nuance.rpc.nlu.v1.InterpretationResource.getDefaultInstance();
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.InterpretationResource build() {
      com.nuance.rpc.nlu.v1.InterpretationResource result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.InterpretationResource buildPartial() {
      com.nuance.rpc.nlu.v1.InterpretationResource result = new com.nuance.rpc.nlu.v1.InterpretationResource(this);
      if (resourceUnionCase_ == 1) {
        if (externalReferenceBuilder_ == null) {
          result.resourceUnion_ = resourceUnion_;
        } else {
          result.resourceUnion_ = externalReferenceBuilder_.build();
        }
      }
      if (resourceUnionCase_ == 2) {
        result.resourceUnion_ = resourceUnion_;
      }
      result.resourceUnionCase_ = resourceUnionCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nuance.rpc.nlu.v1.InterpretationResource) {
        return mergeFrom((com.nuance.rpc.nlu.v1.InterpretationResource)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nuance.rpc.nlu.v1.InterpretationResource other) {
      if (other == com.nuance.rpc.nlu.v1.InterpretationResource.getDefaultInstance()) return this;
      switch (other.getResourceUnionCase()) {
        case EXTERNAL_REFERENCE: {
          mergeExternalReference(other.getExternalReference());
          break;
        }
        case INLINE_WORDSET: {
          resourceUnionCase_ = 2;
          resourceUnion_ = other.resourceUnion_;
          onChanged();
          break;
        }
        case RESOURCEUNION_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nuance.rpc.nlu.v1.InterpretationResource parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nuance.rpc.nlu.v1.InterpretationResource) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int resourceUnionCase_ = 0;
    private java.lang.Object resourceUnion_;
    public ResourceUnionCase
        getResourceUnionCase() {
      return ResourceUnionCase.forNumber(
          resourceUnionCase_);
    }

    public Builder clearResourceUnion() {
      resourceUnionCase_ = 0;
      resourceUnion_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.ResourceReference, com.nuance.rpc.nlu.v1.ResourceReference.Builder, com.nuance.rpc.nlu.v1.ResourceReferenceOrBuilder> externalReferenceBuilder_;
    /**
     * <pre>
     * External resource.
     * </pre>
     *
     * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
     * @return Whether the externalReference field is set.
     */
    public boolean hasExternalReference() {
      return resourceUnionCase_ == 1;
    }
    /**
     * <pre>
     * External resource.
     * </pre>
     *
     * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
     * @return The externalReference.
     */
    public com.nuance.rpc.nlu.v1.ResourceReference getExternalReference() {
      if (externalReferenceBuilder_ == null) {
        if (resourceUnionCase_ == 1) {
          return (com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_;
        }
        return com.nuance.rpc.nlu.v1.ResourceReference.getDefaultInstance();
      } else {
        if (resourceUnionCase_ == 1) {
          return externalReferenceBuilder_.getMessage();
        }
        return com.nuance.rpc.nlu.v1.ResourceReference.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * External resource.
     * </pre>
     *
     * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
     */
    public Builder setExternalReference(com.nuance.rpc.nlu.v1.ResourceReference value) {
      if (externalReferenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resourceUnion_ = value;
        onChanged();
      } else {
        externalReferenceBuilder_.setMessage(value);
      }
      resourceUnionCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * External resource.
     * </pre>
     *
     * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
     */
    public Builder setExternalReference(
        com.nuance.rpc.nlu.v1.ResourceReference.Builder builderForValue) {
      if (externalReferenceBuilder_ == null) {
        resourceUnion_ = builderForValue.build();
        onChanged();
      } else {
        externalReferenceBuilder_.setMessage(builderForValue.build());
      }
      resourceUnionCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * External resource.
     * </pre>
     *
     * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
     */
    public Builder mergeExternalReference(com.nuance.rpc.nlu.v1.ResourceReference value) {
      if (externalReferenceBuilder_ == null) {
        if (resourceUnionCase_ == 1 &&
            resourceUnion_ != com.nuance.rpc.nlu.v1.ResourceReference.getDefaultInstance()) {
          resourceUnion_ = com.nuance.rpc.nlu.v1.ResourceReference.newBuilder((com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_)
              .mergeFrom(value).buildPartial();
        } else {
          resourceUnion_ = value;
        }
        onChanged();
      } else {
        if (resourceUnionCase_ == 1) {
          externalReferenceBuilder_.mergeFrom(value);
        }
        externalReferenceBuilder_.setMessage(value);
      }
      resourceUnionCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * External resource.
     * </pre>
     *
     * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
     */
    public Builder clearExternalReference() {
      if (externalReferenceBuilder_ == null) {
        if (resourceUnionCase_ == 1) {
          resourceUnionCase_ = 0;
          resourceUnion_ = null;
          onChanged();
        }
      } else {
        if (resourceUnionCase_ == 1) {
          resourceUnionCase_ = 0;
          resourceUnion_ = null;
        }
        externalReferenceBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * External resource.
     * </pre>
     *
     * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.ResourceReference.Builder getExternalReferenceBuilder() {
      return getExternalReferenceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * External resource.
     * </pre>
     *
     * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.ResourceReferenceOrBuilder getExternalReferenceOrBuilder() {
      if ((resourceUnionCase_ == 1) && (externalReferenceBuilder_ != null)) {
        return externalReferenceBuilder_.getMessageOrBuilder();
      } else {
        if (resourceUnionCase_ == 1) {
          return (com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_;
        }
        return com.nuance.rpc.nlu.v1.ResourceReference.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * External resource.
     * </pre>
     *
     * <code>.nuance.nlu.v1.ResourceReference external_reference = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.ResourceReference, com.nuance.rpc.nlu.v1.ResourceReference.Builder, com.nuance.rpc.nlu.v1.ResourceReferenceOrBuilder> 
        getExternalReferenceFieldBuilder() {
      if (externalReferenceBuilder_ == null) {
        if (!(resourceUnionCase_ == 1)) {
          resourceUnion_ = com.nuance.rpc.nlu.v1.ResourceReference.getDefaultInstance();
        }
        externalReferenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.nuance.rpc.nlu.v1.ResourceReference, com.nuance.rpc.nlu.v1.ResourceReference.Builder, com.nuance.rpc.nlu.v1.ResourceReferenceOrBuilder>(
                (com.nuance.rpc.nlu.v1.ResourceReference) resourceUnion_,
                getParentForChildren(),
                isClean());
        resourceUnion_ = null;
      }
      resourceUnionCase_ = 1;
      onChanged();;
      return externalReferenceBuilder_;
    }

    /**
     * <pre>
     * Inline wordset, in JSON.
     * </pre>
     *
     * <code>string inline_wordset = 2;</code>
     * @return The inlineWordset.
     */
    public java.lang.String getInlineWordset() {
      java.lang.Object ref = "";
      if (resourceUnionCase_ == 2) {
        ref = resourceUnion_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (resourceUnionCase_ == 2) {
          resourceUnion_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Inline wordset, in JSON.
     * </pre>
     *
     * <code>string inline_wordset = 2;</code>
     * @return The bytes for inlineWordset.
     */
    public com.google.protobuf.ByteString
        getInlineWordsetBytes() {
      java.lang.Object ref = "";
      if (resourceUnionCase_ == 2) {
        ref = resourceUnion_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (resourceUnionCase_ == 2) {
          resourceUnion_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Inline wordset, in JSON.
     * </pre>
     *
     * <code>string inline_wordset = 2;</code>
     * @param value The inlineWordset to set.
     * @return This builder for chaining.
     */
    public Builder setInlineWordset(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  resourceUnionCase_ = 2;
      resourceUnion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Inline wordset, in JSON.
     * </pre>
     *
     * <code>string inline_wordset = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInlineWordset() {
      if (resourceUnionCase_ == 2) {
        resourceUnionCase_ = 0;
        resourceUnion_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Inline wordset, in JSON.
     * </pre>
     *
     * <code>string inline_wordset = 2;</code>
     * @param value The bytes for inlineWordset to set.
     * @return This builder for chaining.
     */
    public Builder setInlineWordsetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      resourceUnionCase_ = 2;
      resourceUnion_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nuance.nlu.v1.InterpretationResource)
  }

  // @@protoc_insertion_point(class_scope:nuance.nlu.v1.InterpretationResource)
  private static final com.nuance.rpc.nlu.v1.InterpretationResource DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nuance.rpc.nlu.v1.InterpretationResource();
  }

  public static com.nuance.rpc.nlu.v1.InterpretationResource getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InterpretationResource>
      PARSER = new com.google.protobuf.AbstractParser<InterpretationResource>() {
    @java.lang.Override
    public InterpretationResource parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InterpretationResource(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InterpretationResource> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InterpretationResource> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nuance.rpc.nlu.v1.InterpretationResource getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

