// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: result.proto

package com.nuance.rpc.nlu.v1;

public interface InterpretResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nuance.nlu.v1.InterpretResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Literal used for interpretation. For text, this is always the raw input text. For ASR as a Service results, a concatenation of the audio tokens, separated by spaces.
   * </pre>
   *
   * <code>string literal = 1;</code>
   * @return The literal.
   */
  java.lang.String getLiteral();
  /**
   * <pre>
   * Literal used for interpretation. For text, this is always the raw input text. For ASR as a Service results, a concatenation of the audio tokens, separated by spaces.
   * </pre>
   *
   * <code>string literal = 1;</code>
   * @return The bytes for literal.
   */
  com.google.protobuf.ByteString
      getLiteralBytes();

  /**
   * <pre>
   * Repeated. Candidate interpretations of the original input.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.Interpretation interpretations = 2;</code>
   */
  java.util.List<com.nuance.rpc.nlu.v1.Interpretation> 
      getInterpretationsList();
  /**
   * <pre>
   * Repeated. Candidate interpretations of the original input.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.Interpretation interpretations = 2;</code>
   */
  com.nuance.rpc.nlu.v1.Interpretation getInterpretations(int index);
  /**
   * <pre>
   * Repeated. Candidate interpretations of the original input.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.Interpretation interpretations = 2;</code>
   */
  int getInterpretationsCount();
  /**
   * <pre>
   * Repeated. Candidate interpretations of the original input.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.Interpretation interpretations = 2;</code>
   */
  java.util.List<? extends com.nuance.rpc.nlu.v1.InterpretationOrBuilder> 
      getInterpretationsOrBuilderList();
  /**
   * <pre>
   * Repeated. Candidate interpretations of the original input.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.Interpretation interpretations = 2;</code>
   */
  com.nuance.rpc.nlu.v1.InterpretationOrBuilder getInterpretationsOrBuilder(
      int index);
}
