// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multi-intent-interpretation.proto

package com.nuance.rpc.nlu.v1;

public interface InterpretationNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nuance.nlu.v1.InterpretationNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The relationship of the intents or entities.
   * </pre>
   *
   * <code>.nuance.nlu.v1.OperatorNode operator = 1;</code>
   * @return Whether the operator field is set.
   */
  boolean hasOperator();
  /**
   * <pre>
   * The relationship of the intents or entities.
   * </pre>
   *
   * <code>.nuance.nlu.v1.OperatorNode operator = 1;</code>
   * @return The operator.
   */
  com.nuance.rpc.nlu.v1.OperatorNode getOperator();
  /**
   * <pre>
   * The relationship of the intents or entities.
   * </pre>
   *
   * <code>.nuance.nlu.v1.OperatorNode operator = 1;</code>
   */
  com.nuance.rpc.nlu.v1.OperatorNodeOrBuilder getOperatorOrBuilder();

  /**
   * <pre>
   * The intents detected in the user input.
   * </pre>
   *
   * <code>.nuance.nlu.v1.IntentNode intent = 2;</code>
   * @return Whether the intent field is set.
   */
  boolean hasIntent();
  /**
   * <pre>
   * The intents detected in the user input.
   * </pre>
   *
   * <code>.nuance.nlu.v1.IntentNode intent = 2;</code>
   * @return The intent.
   */
  com.nuance.rpc.nlu.v1.IntentNode getIntent();
  /**
   * <pre>
   * The intents detected in the user input.
   * </pre>
   *
   * <code>.nuance.nlu.v1.IntentNode intent = 2;</code>
   */
  com.nuance.rpc.nlu.v1.IntentNodeOrBuilder getIntentOrBuilder();

  /**
   * <pre>
   * The entities in the intent.  
   * </pre>
   *
   * <code>.nuance.nlu.v1.EntityNode entity = 3;</code>
   * @return Whether the entity field is set.
   */
  boolean hasEntity();
  /**
   * <pre>
   * The entities in the intent.  
   * </pre>
   *
   * <code>.nuance.nlu.v1.EntityNode entity = 3;</code>
   * @return The entity.
   */
  com.nuance.rpc.nlu.v1.EntityNode getEntity();
  /**
   * <pre>
   * The entities in the intent.  
   * </pre>
   *
   * <code>.nuance.nlu.v1.EntityNode entity = 3;</code>
   */
  com.nuance.rpc.nlu.v1.EntityNodeOrBuilder getEntityOrBuilder();

  public com.nuance.rpc.nlu.v1.InterpretationNode.InterpretationNodeUnionCase getInterpretationNodeUnionCase();
}
