// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: single-intent-interpretation.proto

package com.nuance.rpc.nlu.v1;

/**
 * <pre>
 * List of entities.  Included in
 * [SingleIntentInterpretation](#singleintentinterpretation).
 * </pre>
 *
 * Protobuf type {@code nuance.nlu.v1.SingleIntentEntityList}
 */
public  final class SingleIntentEntityList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nuance.nlu.v1.SingleIntentEntityList)
    SingleIntentEntityListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SingleIntentEntityList.newBuilder() to construct.
  private SingleIntentEntityList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SingleIntentEntityList() {
    entities_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SingleIntentEntityList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SingleIntentEntityList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              entities_ = new java.util.ArrayList<com.nuance.rpc.nlu.v1.SingleIntentEntity>();
              mutable_bitField0_ |= 0x00000001;
            }
            entities_.add(
                input.readMessage(com.nuance.rpc.nlu.v1.SingleIntentEntity.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        entities_ = java.util.Collections.unmodifiableList(entities_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntityList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntityList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nuance.rpc.nlu.v1.SingleIntentEntityList.class, com.nuance.rpc.nlu.v1.SingleIntentEntityList.Builder.class);
  }

  public static final int ENTITIES_FIELD_NUMBER = 1;
  private java.util.List<com.nuance.rpc.nlu.v1.SingleIntentEntity> entities_;
  /**
   * <pre>
   * Repeated. An entity match for the intent, for single-intent interpretation.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
   */
  public java.util.List<com.nuance.rpc.nlu.v1.SingleIntentEntity> getEntitiesList() {
    return entities_;
  }
  /**
   * <pre>
   * Repeated. An entity match for the intent, for single-intent interpretation.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
   */
  public java.util.List<? extends com.nuance.rpc.nlu.v1.SingleIntentEntityOrBuilder> 
      getEntitiesOrBuilderList() {
    return entities_;
  }
  /**
   * <pre>
   * Repeated. An entity match for the intent, for single-intent interpretation.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
   */
  public int getEntitiesCount() {
    return entities_.size();
  }
  /**
   * <pre>
   * Repeated. An entity match for the intent, for single-intent interpretation.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
   */
  public com.nuance.rpc.nlu.v1.SingleIntentEntity getEntities(int index) {
    return entities_.get(index);
  }
  /**
   * <pre>
   * Repeated. An entity match for the intent, for single-intent interpretation.
   * </pre>
   *
   * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
   */
  public com.nuance.rpc.nlu.v1.SingleIntentEntityOrBuilder getEntitiesOrBuilder(
      int index) {
    return entities_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entities_.size(); i++) {
      output.writeMessage(1, entities_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entities_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, entities_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nuance.rpc.nlu.v1.SingleIntentEntityList)) {
      return super.equals(obj);
    }
    com.nuance.rpc.nlu.v1.SingleIntentEntityList other = (com.nuance.rpc.nlu.v1.SingleIntentEntityList) obj;

    if (!getEntitiesList()
        .equals(other.getEntitiesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntitiesCount() > 0) {
      hash = (37 * hash) + ENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntitiesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nuance.rpc.nlu.v1.SingleIntentEntityList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * List of entities.  Included in
   * [SingleIntentInterpretation](#singleintentinterpretation).
   * </pre>
   *
   * Protobuf type {@code nuance.nlu.v1.SingleIntentEntityList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nuance.nlu.v1.SingleIntentEntityList)
      com.nuance.rpc.nlu.v1.SingleIntentEntityListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntityList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntityList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nuance.rpc.nlu.v1.SingleIntentEntityList.class, com.nuance.rpc.nlu.v1.SingleIntentEntityList.Builder.class);
    }

    // Construct using com.nuance.rpc.nlu.v1.SingleIntentEntityList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEntitiesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (entitiesBuilder_ == null) {
        entities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        entitiesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntityList_descriptor;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.SingleIntentEntityList getDefaultInstanceForType() {
      return com.nuance.rpc.nlu.v1.SingleIntentEntityList.getDefaultInstance();
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.SingleIntentEntityList build() {
      com.nuance.rpc.nlu.v1.SingleIntentEntityList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.SingleIntentEntityList buildPartial() {
      com.nuance.rpc.nlu.v1.SingleIntentEntityList result = new com.nuance.rpc.nlu.v1.SingleIntentEntityList(this);
      int from_bitField0_ = bitField0_;
      if (entitiesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          entities_ = java.util.Collections.unmodifiableList(entities_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entities_ = entities_;
      } else {
        result.entities_ = entitiesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nuance.rpc.nlu.v1.SingleIntentEntityList) {
        return mergeFrom((com.nuance.rpc.nlu.v1.SingleIntentEntityList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nuance.rpc.nlu.v1.SingleIntentEntityList other) {
      if (other == com.nuance.rpc.nlu.v1.SingleIntentEntityList.getDefaultInstance()) return this;
      if (entitiesBuilder_ == null) {
        if (!other.entities_.isEmpty()) {
          if (entities_.isEmpty()) {
            entities_ = other.entities_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntitiesIsMutable();
            entities_.addAll(other.entities_);
          }
          onChanged();
        }
      } else {
        if (!other.entities_.isEmpty()) {
          if (entitiesBuilder_.isEmpty()) {
            entitiesBuilder_.dispose();
            entitiesBuilder_ = null;
            entities_ = other.entities_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entitiesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntitiesFieldBuilder() : null;
          } else {
            entitiesBuilder_.addAllMessages(other.entities_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nuance.rpc.nlu.v1.SingleIntentEntityList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nuance.rpc.nlu.v1.SingleIntentEntityList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.nuance.rpc.nlu.v1.SingleIntentEntity> entities_ =
      java.util.Collections.emptyList();
    private void ensureEntitiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entities_ = new java.util.ArrayList<com.nuance.rpc.nlu.v1.SingleIntentEntity>(entities_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nuance.rpc.nlu.v1.SingleIntentEntity, com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder, com.nuance.rpc.nlu.v1.SingleIntentEntityOrBuilder> entitiesBuilder_;

    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public java.util.List<com.nuance.rpc.nlu.v1.SingleIntentEntity> getEntitiesList() {
      if (entitiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entities_);
      } else {
        return entitiesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public int getEntitiesCount() {
      if (entitiesBuilder_ == null) {
        return entities_.size();
      } else {
        return entitiesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.SingleIntentEntity getEntities(int index) {
      if (entitiesBuilder_ == null) {
        return entities_.get(index);
      } else {
        return entitiesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public Builder setEntities(
        int index, com.nuance.rpc.nlu.v1.SingleIntentEntity value) {
      if (entitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntitiesIsMutable();
        entities_.set(index, value);
        onChanged();
      } else {
        entitiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public Builder setEntities(
        int index, com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder builderForValue) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        entities_.set(index, builderForValue.build());
        onChanged();
      } else {
        entitiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public Builder addEntities(com.nuance.rpc.nlu.v1.SingleIntentEntity value) {
      if (entitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntitiesIsMutable();
        entities_.add(value);
        onChanged();
      } else {
        entitiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public Builder addEntities(
        int index, com.nuance.rpc.nlu.v1.SingleIntentEntity value) {
      if (entitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntitiesIsMutable();
        entities_.add(index, value);
        onChanged();
      } else {
        entitiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public Builder addEntities(
        com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder builderForValue) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        entities_.add(builderForValue.build());
        onChanged();
      } else {
        entitiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public Builder addEntities(
        int index, com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder builderForValue) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        entities_.add(index, builderForValue.build());
        onChanged();
      } else {
        entitiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public Builder addAllEntities(
        java.lang.Iterable<? extends com.nuance.rpc.nlu.v1.SingleIntentEntity> values) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entities_);
        onChanged();
      } else {
        entitiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public Builder clearEntities() {
      if (entitiesBuilder_ == null) {
        entities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entitiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public Builder removeEntities(int index) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        entities_.remove(index);
        onChanged();
      } else {
        entitiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder getEntitiesBuilder(
        int index) {
      return getEntitiesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.SingleIntentEntityOrBuilder getEntitiesOrBuilder(
        int index) {
      if (entitiesBuilder_ == null) {
        return entities_.get(index);  } else {
        return entitiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public java.util.List<? extends com.nuance.rpc.nlu.v1.SingleIntentEntityOrBuilder> 
         getEntitiesOrBuilderList() {
      if (entitiesBuilder_ != null) {
        return entitiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entities_);
      }
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder addEntitiesBuilder() {
      return getEntitiesFieldBuilder().addBuilder(
          com.nuance.rpc.nlu.v1.SingleIntentEntity.getDefaultInstance());
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder addEntitiesBuilder(
        int index) {
      return getEntitiesFieldBuilder().addBuilder(
          index, com.nuance.rpc.nlu.v1.SingleIntentEntity.getDefaultInstance());
    }
    /**
     * <pre>
     * Repeated. An entity match for the intent, for single-intent interpretation.
     * </pre>
     *
     * <code>repeated .nuance.nlu.v1.SingleIntentEntity entities = 1;</code>
     */
    public java.util.List<com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder> 
         getEntitiesBuilderList() {
      return getEntitiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.nuance.rpc.nlu.v1.SingleIntentEntity, com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder, com.nuance.rpc.nlu.v1.SingleIntentEntityOrBuilder> 
        getEntitiesFieldBuilder() {
      if (entitiesBuilder_ == null) {
        entitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.nuance.rpc.nlu.v1.SingleIntentEntity, com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder, com.nuance.rpc.nlu.v1.SingleIntentEntityOrBuilder>(
                entities_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        entities_ = null;
      }
      return entitiesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nuance.nlu.v1.SingleIntentEntityList)
  }

  // @@protoc_insertion_point(class_scope:nuance.nlu.v1.SingleIntentEntityList)
  private static final com.nuance.rpc.nlu.v1.SingleIntentEntityList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nuance.rpc.nlu.v1.SingleIntentEntityList();
  }

  public static com.nuance.rpc.nlu.v1.SingleIntentEntityList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SingleIntentEntityList>
      PARSER = new com.google.protobuf.AbstractParser<SingleIntentEntityList>() {
    @java.lang.Override
    public SingleIntentEntityList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SingleIntentEntityList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SingleIntentEntityList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SingleIntentEntityList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nuance.rpc.nlu.v1.SingleIntentEntityList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

