// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: single-intent-interpretation.proto

package com.nuance.rpc.nlu.v1;

/**
 * <pre>
 * Entity in the intent. Included in
 * [SingleIntentEntityList](#singleintententitylist).
 * </pre>
 *
 * Protobuf type {@code nuance.nlu.v1.SingleIntentEntity}
 */
public  final class SingleIntentEntity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nuance.nlu.v1.SingleIntentEntity)
    SingleIntentEntityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SingleIntentEntity.newBuilder() to construct.
  private SingleIntentEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SingleIntentEntity() {
    origin_ = 0;
    literal_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SingleIntentEntity();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SingleIntentEntity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.nuance.rpc.nlu.v1.TextRange.Builder subBuilder = null;
            if (textRange_ != null) {
              subBuilder = textRange_.toBuilder();
            }
            textRange_ = input.readMessage(com.nuance.rpc.nlu.v1.TextRange.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(textRange_);
              textRange_ = subBuilder.buildPartial();
            }

            break;
          }
          case 29: {

            confidence_ = input.readFloat();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            origin_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              entities_ = com.google.protobuf.MapField.newMapField(
                  EntitiesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList>
            entities__ = input.readMessage(
                EntitiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            entities_.getMutableMap().put(
                entities__.getKey(), entities__.getValue());
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            valueUnionCase_ = 6;
            valueUnion_ = s;
            break;
          }
          case 58: {
            com.google.protobuf.Struct.Builder subBuilder = null;
            if (valueUnionCase_ == 7) {
              subBuilder = ((com.google.protobuf.Struct) valueUnion_).toBuilder();
            }
            valueUnion_ =
                input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Struct) valueUnion_);
              valueUnion_ = subBuilder.buildPartial();
            }
            valueUnionCase_ = 7;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            literal_ = s;
            break;
          }
          case 122: {
            com.nuance.rpc.nlu.v1.AudioRange.Builder subBuilder = null;
            if (audioRange_ != null) {
              subBuilder = audioRange_.toBuilder();
            }
            audioRange_ = input.readMessage(com.nuance.rpc.nlu.v1.AudioRange.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(audioRange_);
              audioRange_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntity_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetEntities();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nuance.rpc.nlu.v1.SingleIntentEntity.class, com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder.class);
  }

  private int valueUnionCase_ = 0;
  private java.lang.Object valueUnion_;
  public enum ValueUnionCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STRING_VALUE(6),
    STRUCT_VALUE(7),
    VALUEUNION_NOT_SET(0);
    private final int value;
    private ValueUnionCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueUnionCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueUnionCase forNumber(int value) {
      switch (value) {
        case 6: return STRING_VALUE;
        case 7: return STRUCT_VALUE;
        case 0: return VALUEUNION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueUnionCase
  getValueUnionCase() {
    return ValueUnionCase.forNumber(
        valueUnionCase_);
  }

  public static final int TEXT_RANGE_FIELD_NUMBER = 1;
  private com.nuance.rpc.nlu.v1.TextRange textRange_;
  /**
   * <pre>
   * Range of literal text for which this entity applies.
   * </pre>
   *
   * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
   * @return Whether the textRange field is set.
   */
  public boolean hasTextRange() {
    return textRange_ != null;
  }
  /**
   * <pre>
   * Range of literal text for which this entity applies.
   * </pre>
   *
   * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
   * @return The textRange.
   */
  public com.nuance.rpc.nlu.v1.TextRange getTextRange() {
    return textRange_ == null ? com.nuance.rpc.nlu.v1.TextRange.getDefaultInstance() : textRange_;
  }
  /**
   * <pre>
   * Range of literal text for which this entity applies.
   * </pre>
   *
   * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
   */
  public com.nuance.rpc.nlu.v1.TextRangeOrBuilder getTextRangeOrBuilder() {
    return getTextRange();
  }

  public static final int CONFIDENCE_FIELD_NUMBER = 3;
  private float confidence_;
  /**
   * <pre>
   * Confidence score between 0.0 and 1.0 inclusive. The higher the score, the likelier the entity detection is correct.
   * </pre>
   *
   * <code>float confidence = 3;</code>
   * @return The confidence.
   */
  public float getConfidence() {
    return confidence_;
  }

  public static final int ORIGIN_FIELD_NUMBER = 4;
  private int origin_;
  /**
   * <pre>
   * How the entity was detected.
   * </pre>
   *
   * <code>.nuance.nlu.v1.EnumOrigin origin = 4;</code>
   * @return The enum numeric value on the wire for origin.
   */
  public int getOriginValue() {
    return origin_;
  }
  /**
   * <pre>
   * How the entity was detected.
   * </pre>
   *
   * <code>.nuance.nlu.v1.EnumOrigin origin = 4;</code>
   * @return The origin.
   */
  public com.nuance.rpc.nlu.v1.EnumOrigin getOrigin() {
    @SuppressWarnings("deprecation")
    com.nuance.rpc.nlu.v1.EnumOrigin result = com.nuance.rpc.nlu.v1.EnumOrigin.valueOf(origin_);
    return result == null ? com.nuance.rpc.nlu.v1.EnumOrigin.UNRECOGNIZED : result;
  }

  public static final int ENTITIES_FIELD_NUMBER = 5;
  private static final class EntitiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList>newDefaultInstance(
                com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntity_EntitiesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.nuance.rpc.nlu.v1.SingleIntentEntityList.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> entities_;
  private com.google.protobuf.MapField<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList>
  internalGetEntities() {
    if (entities_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EntitiesDefaultEntryHolder.defaultEntry);
    }
    return entities_;
  }

  public int getEntitiesCount() {
    return internalGetEntities().getMap().size();
  }
  /**
   * <pre>
   * For hierarchical entities, the child entities of the entity.
   * </pre>
   *
   * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
   */

  public boolean containsEntities(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetEntities().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEntitiesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> getEntities() {
    return getEntitiesMap();
  }
  /**
   * <pre>
   * For hierarchical entities, the child entities of the entity.
   * </pre>
   *
   * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
   */

  public java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> getEntitiesMap() {
    return internalGetEntities().getMap();
  }
  /**
   * <pre>
   * For hierarchical entities, the child entities of the entity.
   * </pre>
   *
   * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
   */

  public com.nuance.rpc.nlu.v1.SingleIntentEntityList getEntitiesOrDefault(
      java.lang.String key,
      com.nuance.rpc.nlu.v1.SingleIntentEntityList defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> map =
        internalGetEntities().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * For hierarchical entities, the child entities of the entity.
   * </pre>
   *
   * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
   */

  public com.nuance.rpc.nlu.v1.SingleIntentEntityList getEntitiesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> map =
        internalGetEntities().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int STRING_VALUE_FIELD_NUMBER = 6;
  /**
   * <pre>
   * The canonical value as a string.
   * </pre>
   *
   * <code>string string_value = 6;</code>
   * @return The stringValue.
   */
  public java.lang.String getStringValue() {
    java.lang.Object ref = "";
    if (valueUnionCase_ == 6) {
      ref = valueUnion_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (valueUnionCase_ == 6) {
        valueUnion_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The canonical value as a string.
   * </pre>
   *
   * <code>string string_value = 6;</code>
   * @return The bytes for stringValue.
   */
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.Object ref = "";
    if (valueUnionCase_ == 6) {
      ref = valueUnion_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (valueUnionCase_ == 6) {
        valueUnion_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRUCT_VALUE_FIELD_NUMBER = 7;
  /**
   * <pre>
   * The entity value as an object. This object may be directly converted to a JSON representation.
   * </pre>
   *
   * <code>.google.protobuf.Struct struct_value = 7;</code>
   * @return Whether the structValue field is set.
   */
  public boolean hasStructValue() {
    return valueUnionCase_ == 7;
  }
  /**
   * <pre>
   * The entity value as an object. This object may be directly converted to a JSON representation.
   * </pre>
   *
   * <code>.google.protobuf.Struct struct_value = 7;</code>
   * @return The structValue.
   */
  public com.google.protobuf.Struct getStructValue() {
    if (valueUnionCase_ == 7) {
       return (com.google.protobuf.Struct) valueUnion_;
    }
    return com.google.protobuf.Struct.getDefaultInstance();
  }
  /**
   * <pre>
   * The entity value as an object. This object may be directly converted to a JSON representation.
   * </pre>
   *
   * <code>.google.protobuf.Struct struct_value = 7;</code>
   */
  public com.google.protobuf.StructOrBuilder getStructValueOrBuilder() {
    if (valueUnionCase_ == 7) {
       return (com.google.protobuf.Struct) valueUnion_;
    }
    return com.google.protobuf.Struct.getDefaultInstance();
  }

  public static final int LITERAL_FIELD_NUMBER = 8;
  private volatile java.lang.Object literal_;
  /**
   * <pre>
   * The input literal associated with this entity.
   * </pre>
   *
   * <code>string literal = 8;</code>
   * @return The literal.
   */
  public java.lang.String getLiteral() {
    java.lang.Object ref = literal_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      literal_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The input literal associated with this entity.
   * </pre>
   *
   * <code>string literal = 8;</code>
   * @return The bytes for literal.
   */
  public com.google.protobuf.ByteString
      getLiteralBytes() {
    java.lang.Object ref = literal_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      literal_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUDIO_RANGE_FIELD_NUMBER = 15;
  private com.nuance.rpc.nlu.v1.AudioRange audioRange_;
  /**
   * <pre>
   * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
   * </pre>
   *
   * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
   * @return Whether the audioRange field is set.
   */
  public boolean hasAudioRange() {
    return audioRange_ != null;
  }
  /**
   * <pre>
   * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
   * </pre>
   *
   * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
   * @return The audioRange.
   */
  public com.nuance.rpc.nlu.v1.AudioRange getAudioRange() {
    return audioRange_ == null ? com.nuance.rpc.nlu.v1.AudioRange.getDefaultInstance() : audioRange_;
  }
  /**
   * <pre>
   * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
   * </pre>
   *
   * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
   */
  public com.nuance.rpc.nlu.v1.AudioRangeOrBuilder getAudioRangeOrBuilder() {
    return getAudioRange();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (textRange_ != null) {
      output.writeMessage(1, getTextRange());
    }
    if (confidence_ != 0F) {
      output.writeFloat(3, confidence_);
    }
    if (origin_ != com.nuance.rpc.nlu.v1.EnumOrigin.UNKNOWN.getNumber()) {
      output.writeEnum(4, origin_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEntities(),
        EntitiesDefaultEntryHolder.defaultEntry,
        5);
    if (valueUnionCase_ == 6) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, valueUnion_);
    }
    if (valueUnionCase_ == 7) {
      output.writeMessage(7, (com.google.protobuf.Struct) valueUnion_);
    }
    if (!getLiteralBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, literal_);
    }
    if (audioRange_ != null) {
      output.writeMessage(15, getAudioRange());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (textRange_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTextRange());
    }
    if (confidence_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, confidence_);
    }
    if (origin_ != com.nuance.rpc.nlu.v1.EnumOrigin.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, origin_);
    }
    for (java.util.Map.Entry<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> entry
         : internalGetEntities().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList>
      entities__ = EntitiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, entities__);
    }
    if (valueUnionCase_ == 6) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, valueUnion_);
    }
    if (valueUnionCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.google.protobuf.Struct) valueUnion_);
    }
    if (!getLiteralBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, literal_);
    }
    if (audioRange_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getAudioRange());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nuance.rpc.nlu.v1.SingleIntentEntity)) {
      return super.equals(obj);
    }
    com.nuance.rpc.nlu.v1.SingleIntentEntity other = (com.nuance.rpc.nlu.v1.SingleIntentEntity) obj;

    if (hasTextRange() != other.hasTextRange()) return false;
    if (hasTextRange()) {
      if (!getTextRange()
          .equals(other.getTextRange())) return false;
    }
    if (java.lang.Float.floatToIntBits(getConfidence())
        != java.lang.Float.floatToIntBits(
            other.getConfidence())) return false;
    if (origin_ != other.origin_) return false;
    if (!internalGetEntities().equals(
        other.internalGetEntities())) return false;
    if (!getLiteral()
        .equals(other.getLiteral())) return false;
    if (hasAudioRange() != other.hasAudioRange()) return false;
    if (hasAudioRange()) {
      if (!getAudioRange()
          .equals(other.getAudioRange())) return false;
    }
    if (!getValueUnionCase().equals(other.getValueUnionCase())) return false;
    switch (valueUnionCase_) {
      case 6:
        if (!getStringValue()
            .equals(other.getStringValue())) return false;
        break;
      case 7:
        if (!getStructValue()
            .equals(other.getStructValue())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTextRange()) {
      hash = (37 * hash) + TEXT_RANGE_FIELD_NUMBER;
      hash = (53 * hash) + getTextRange().hashCode();
    }
    hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getConfidence());
    hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
    hash = (53 * hash) + origin_;
    if (!internalGetEntities().getMap().isEmpty()) {
      hash = (37 * hash) + ENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEntities().hashCode();
    }
    hash = (37 * hash) + LITERAL_FIELD_NUMBER;
    hash = (53 * hash) + getLiteral().hashCode();
    if (hasAudioRange()) {
      hash = (37 * hash) + AUDIO_RANGE_FIELD_NUMBER;
      hash = (53 * hash) + getAudioRange().hashCode();
    }
    switch (valueUnionCase_) {
      case 6:
        hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValue().hashCode();
        break;
      case 7:
        hash = (37 * hash) + STRUCT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStructValue().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nuance.rpc.nlu.v1.SingleIntentEntity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nuance.rpc.nlu.v1.SingleIntentEntity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Entity in the intent. Included in
   * [SingleIntentEntityList](#singleintententitylist).
   * </pre>
   *
   * Protobuf type {@code nuance.nlu.v1.SingleIntentEntity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nuance.nlu.v1.SingleIntentEntity)
      com.nuance.rpc.nlu.v1.SingleIntentEntityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntity_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetEntities();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableEntities();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nuance.rpc.nlu.v1.SingleIntentEntity.class, com.nuance.rpc.nlu.v1.SingleIntentEntity.Builder.class);
    }

    // Construct using com.nuance.rpc.nlu.v1.SingleIntentEntity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (textRangeBuilder_ == null) {
        textRange_ = null;
      } else {
        textRange_ = null;
        textRangeBuilder_ = null;
      }
      confidence_ = 0F;

      origin_ = 0;

      internalGetMutableEntities().clear();
      literal_ = "";

      if (audioRangeBuilder_ == null) {
        audioRange_ = null;
      } else {
        audioRange_ = null;
        audioRangeBuilder_ = null;
      }
      valueUnionCase_ = 0;
      valueUnion_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nuance.rpc.nlu.v1.SingleIntentInterpretationProto.internal_static_nuance_nlu_v1_SingleIntentEntity_descriptor;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.SingleIntentEntity getDefaultInstanceForType() {
      return com.nuance.rpc.nlu.v1.SingleIntentEntity.getDefaultInstance();
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.SingleIntentEntity build() {
      com.nuance.rpc.nlu.v1.SingleIntentEntity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nuance.rpc.nlu.v1.SingleIntentEntity buildPartial() {
      com.nuance.rpc.nlu.v1.SingleIntentEntity result = new com.nuance.rpc.nlu.v1.SingleIntentEntity(this);
      int from_bitField0_ = bitField0_;
      if (textRangeBuilder_ == null) {
        result.textRange_ = textRange_;
      } else {
        result.textRange_ = textRangeBuilder_.build();
      }
      result.confidence_ = confidence_;
      result.origin_ = origin_;
      result.entities_ = internalGetEntities();
      result.entities_.makeImmutable();
      if (valueUnionCase_ == 6) {
        result.valueUnion_ = valueUnion_;
      }
      if (valueUnionCase_ == 7) {
        if (structValueBuilder_ == null) {
          result.valueUnion_ = valueUnion_;
        } else {
          result.valueUnion_ = structValueBuilder_.build();
        }
      }
      result.literal_ = literal_;
      if (audioRangeBuilder_ == null) {
        result.audioRange_ = audioRange_;
      } else {
        result.audioRange_ = audioRangeBuilder_.build();
      }
      result.valueUnionCase_ = valueUnionCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nuance.rpc.nlu.v1.SingleIntentEntity) {
        return mergeFrom((com.nuance.rpc.nlu.v1.SingleIntentEntity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nuance.rpc.nlu.v1.SingleIntentEntity other) {
      if (other == com.nuance.rpc.nlu.v1.SingleIntentEntity.getDefaultInstance()) return this;
      if (other.hasTextRange()) {
        mergeTextRange(other.getTextRange());
      }
      if (other.getConfidence() != 0F) {
        setConfidence(other.getConfidence());
      }
      if (other.origin_ != 0) {
        setOriginValue(other.getOriginValue());
      }
      internalGetMutableEntities().mergeFrom(
          other.internalGetEntities());
      if (!other.getLiteral().isEmpty()) {
        literal_ = other.literal_;
        onChanged();
      }
      if (other.hasAudioRange()) {
        mergeAudioRange(other.getAudioRange());
      }
      switch (other.getValueUnionCase()) {
        case STRING_VALUE: {
          valueUnionCase_ = 6;
          valueUnion_ = other.valueUnion_;
          onChanged();
          break;
        }
        case STRUCT_VALUE: {
          mergeStructValue(other.getStructValue());
          break;
        }
        case VALUEUNION_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nuance.rpc.nlu.v1.SingleIntentEntity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nuance.rpc.nlu.v1.SingleIntentEntity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int valueUnionCase_ = 0;
    private java.lang.Object valueUnion_;
    public ValueUnionCase
        getValueUnionCase() {
      return ValueUnionCase.forNumber(
          valueUnionCase_);
    }

    public Builder clearValueUnion() {
      valueUnionCase_ = 0;
      valueUnion_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.nuance.rpc.nlu.v1.TextRange textRange_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.TextRange, com.nuance.rpc.nlu.v1.TextRange.Builder, com.nuance.rpc.nlu.v1.TextRangeOrBuilder> textRangeBuilder_;
    /**
     * <pre>
     * Range of literal text for which this entity applies.
     * </pre>
     *
     * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
     * @return Whether the textRange field is set.
     */
    public boolean hasTextRange() {
      return textRangeBuilder_ != null || textRange_ != null;
    }
    /**
     * <pre>
     * Range of literal text for which this entity applies.
     * </pre>
     *
     * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
     * @return The textRange.
     */
    public com.nuance.rpc.nlu.v1.TextRange getTextRange() {
      if (textRangeBuilder_ == null) {
        return textRange_ == null ? com.nuance.rpc.nlu.v1.TextRange.getDefaultInstance() : textRange_;
      } else {
        return textRangeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Range of literal text for which this entity applies.
     * </pre>
     *
     * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
     */
    public Builder setTextRange(com.nuance.rpc.nlu.v1.TextRange value) {
      if (textRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        textRange_ = value;
        onChanged();
      } else {
        textRangeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Range of literal text for which this entity applies.
     * </pre>
     *
     * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
     */
    public Builder setTextRange(
        com.nuance.rpc.nlu.v1.TextRange.Builder builderForValue) {
      if (textRangeBuilder_ == null) {
        textRange_ = builderForValue.build();
        onChanged();
      } else {
        textRangeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Range of literal text for which this entity applies.
     * </pre>
     *
     * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
     */
    public Builder mergeTextRange(com.nuance.rpc.nlu.v1.TextRange value) {
      if (textRangeBuilder_ == null) {
        if (textRange_ != null) {
          textRange_ =
            com.nuance.rpc.nlu.v1.TextRange.newBuilder(textRange_).mergeFrom(value).buildPartial();
        } else {
          textRange_ = value;
        }
        onChanged();
      } else {
        textRangeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Range of literal text for which this entity applies.
     * </pre>
     *
     * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
     */
    public Builder clearTextRange() {
      if (textRangeBuilder_ == null) {
        textRange_ = null;
        onChanged();
      } else {
        textRange_ = null;
        textRangeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Range of literal text for which this entity applies.
     * </pre>
     *
     * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.TextRange.Builder getTextRangeBuilder() {
      
      onChanged();
      return getTextRangeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Range of literal text for which this entity applies.
     * </pre>
     *
     * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
     */
    public com.nuance.rpc.nlu.v1.TextRangeOrBuilder getTextRangeOrBuilder() {
      if (textRangeBuilder_ != null) {
        return textRangeBuilder_.getMessageOrBuilder();
      } else {
        return textRange_ == null ?
            com.nuance.rpc.nlu.v1.TextRange.getDefaultInstance() : textRange_;
      }
    }
    /**
     * <pre>
     * Range of literal text for which this entity applies.
     * </pre>
     *
     * <code>.nuance.nlu.v1.TextRange text_range = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.TextRange, com.nuance.rpc.nlu.v1.TextRange.Builder, com.nuance.rpc.nlu.v1.TextRangeOrBuilder> 
        getTextRangeFieldBuilder() {
      if (textRangeBuilder_ == null) {
        textRangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.nuance.rpc.nlu.v1.TextRange, com.nuance.rpc.nlu.v1.TextRange.Builder, com.nuance.rpc.nlu.v1.TextRangeOrBuilder>(
                getTextRange(),
                getParentForChildren(),
                isClean());
        textRange_ = null;
      }
      return textRangeBuilder_;
    }

    private float confidence_ ;
    /**
     * <pre>
     * Confidence score between 0.0 and 1.0 inclusive. The higher the score, the likelier the entity detection is correct.
     * </pre>
     *
     * <code>float confidence = 3;</code>
     * @return The confidence.
     */
    public float getConfidence() {
      return confidence_;
    }
    /**
     * <pre>
     * Confidence score between 0.0 and 1.0 inclusive. The higher the score, the likelier the entity detection is correct.
     * </pre>
     *
     * <code>float confidence = 3;</code>
     * @param value The confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidence(float value) {
      
      confidence_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Confidence score between 0.0 and 1.0 inclusive. The higher the score, the likelier the entity detection is correct.
     * </pre>
     *
     * <code>float confidence = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfidence() {
      
      confidence_ = 0F;
      onChanged();
      return this;
    }

    private int origin_ = 0;
    /**
     * <pre>
     * How the entity was detected.
     * </pre>
     *
     * <code>.nuance.nlu.v1.EnumOrigin origin = 4;</code>
     * @return The enum numeric value on the wire for origin.
     */
    public int getOriginValue() {
      return origin_;
    }
    /**
     * <pre>
     * How the entity was detected.
     * </pre>
     *
     * <code>.nuance.nlu.v1.EnumOrigin origin = 4;</code>
     * @param value The enum numeric value on the wire for origin to set.
     * @return This builder for chaining.
     */
    public Builder setOriginValue(int value) {
      origin_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How the entity was detected.
     * </pre>
     *
     * <code>.nuance.nlu.v1.EnumOrigin origin = 4;</code>
     * @return The origin.
     */
    public com.nuance.rpc.nlu.v1.EnumOrigin getOrigin() {
      @SuppressWarnings("deprecation")
      com.nuance.rpc.nlu.v1.EnumOrigin result = com.nuance.rpc.nlu.v1.EnumOrigin.valueOf(origin_);
      return result == null ? com.nuance.rpc.nlu.v1.EnumOrigin.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * How the entity was detected.
     * </pre>
     *
     * <code>.nuance.nlu.v1.EnumOrigin origin = 4;</code>
     * @param value The origin to set.
     * @return This builder for chaining.
     */
    public Builder setOrigin(com.nuance.rpc.nlu.v1.EnumOrigin value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      origin_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How the entity was detected.
     * </pre>
     *
     * <code>.nuance.nlu.v1.EnumOrigin origin = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrigin() {
      
      origin_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> entities_;
    private com.google.protobuf.MapField<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList>
    internalGetEntities() {
      if (entities_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EntitiesDefaultEntryHolder.defaultEntry);
      }
      return entities_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList>
    internalGetMutableEntities() {
      onChanged();;
      if (entities_ == null) {
        entities_ = com.google.protobuf.MapField.newMapField(
            EntitiesDefaultEntryHolder.defaultEntry);
      }
      if (!entities_.isMutable()) {
        entities_ = entities_.copy();
      }
      return entities_;
    }

    public int getEntitiesCount() {
      return internalGetEntities().getMap().size();
    }
    /**
     * <pre>
     * For hierarchical entities, the child entities of the entity.
     * </pre>
     *
     * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
     */

    public boolean containsEntities(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetEntities().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEntitiesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> getEntities() {
      return getEntitiesMap();
    }
    /**
     * <pre>
     * For hierarchical entities, the child entities of the entity.
     * </pre>
     *
     * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
     */

    public java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> getEntitiesMap() {
      return internalGetEntities().getMap();
    }
    /**
     * <pre>
     * For hierarchical entities, the child entities of the entity.
     * </pre>
     *
     * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
     */

    public com.nuance.rpc.nlu.v1.SingleIntentEntityList getEntitiesOrDefault(
        java.lang.String key,
        com.nuance.rpc.nlu.v1.SingleIntentEntityList defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> map =
          internalGetEntities().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * For hierarchical entities, the child entities of the entity.
     * </pre>
     *
     * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
     */

    public com.nuance.rpc.nlu.v1.SingleIntentEntityList getEntitiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> map =
          internalGetEntities().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearEntities() {
      internalGetMutableEntities().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * For hierarchical entities, the child entities of the entity.
     * </pre>
     *
     * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
     */

    public Builder removeEntities(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableEntities().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList>
    getMutableEntities() {
      return internalGetMutableEntities().getMutableMap();
    }
    /**
     * <pre>
     * For hierarchical entities, the child entities of the entity.
     * </pre>
     *
     * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
     */
    public Builder putEntities(
        java.lang.String key,
        com.nuance.rpc.nlu.v1.SingleIntentEntityList value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableEntities().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * For hierarchical entities, the child entities of the entity.
     * </pre>
     *
     * <code>map&lt;string, .nuance.nlu.v1.SingleIntentEntityList&gt; entities = 5;</code>
     */

    public Builder putAllEntities(
        java.util.Map<java.lang.String, com.nuance.rpc.nlu.v1.SingleIntentEntityList> values) {
      internalGetMutableEntities().getMutableMap()
          .putAll(values);
      return this;
    }

    /**
     * <pre>
     * The canonical value as a string.
     * </pre>
     *
     * <code>string string_value = 6;</code>
     * @return The stringValue.
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (valueUnionCase_ == 6) {
        ref = valueUnion_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueUnionCase_ == 6) {
          valueUnion_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The canonical value as a string.
     * </pre>
     *
     * <code>string string_value = 6;</code>
     * @return The bytes for stringValue.
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (valueUnionCase_ == 6) {
        ref = valueUnion_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueUnionCase_ == 6) {
          valueUnion_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The canonical value as a string.
     * </pre>
     *
     * <code>string string_value = 6;</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valueUnionCase_ = 6;
      valueUnion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The canonical value as a string.
     * </pre>
     *
     * <code>string string_value = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      if (valueUnionCase_ == 6) {
        valueUnionCase_ = 0;
        valueUnion_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The canonical value as a string.
     * </pre>
     *
     * <code>string string_value = 6;</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      valueUnionCase_ = 6;
      valueUnion_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> structValueBuilder_;
    /**
     * <pre>
     * The entity value as an object. This object may be directly converted to a JSON representation.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 7;</code>
     * @return Whether the structValue field is set.
     */
    public boolean hasStructValue() {
      return valueUnionCase_ == 7;
    }
    /**
     * <pre>
     * The entity value as an object. This object may be directly converted to a JSON representation.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 7;</code>
     * @return The structValue.
     */
    public com.google.protobuf.Struct getStructValue() {
      if (structValueBuilder_ == null) {
        if (valueUnionCase_ == 7) {
          return (com.google.protobuf.Struct) valueUnion_;
        }
        return com.google.protobuf.Struct.getDefaultInstance();
      } else {
        if (valueUnionCase_ == 7) {
          return structValueBuilder_.getMessage();
        }
        return com.google.protobuf.Struct.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The entity value as an object. This object may be directly converted to a JSON representation.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 7;</code>
     */
    public Builder setStructValue(com.google.protobuf.Struct value) {
      if (structValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        valueUnion_ = value;
        onChanged();
      } else {
        structValueBuilder_.setMessage(value);
      }
      valueUnionCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * The entity value as an object. This object may be directly converted to a JSON representation.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 7;</code>
     */
    public Builder setStructValue(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (structValueBuilder_ == null) {
        valueUnion_ = builderForValue.build();
        onChanged();
      } else {
        structValueBuilder_.setMessage(builderForValue.build());
      }
      valueUnionCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * The entity value as an object. This object may be directly converted to a JSON representation.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 7;</code>
     */
    public Builder mergeStructValue(com.google.protobuf.Struct value) {
      if (structValueBuilder_ == null) {
        if (valueUnionCase_ == 7 &&
            valueUnion_ != com.google.protobuf.Struct.getDefaultInstance()) {
          valueUnion_ = com.google.protobuf.Struct.newBuilder((com.google.protobuf.Struct) valueUnion_)
              .mergeFrom(value).buildPartial();
        } else {
          valueUnion_ = value;
        }
        onChanged();
      } else {
        if (valueUnionCase_ == 7) {
          structValueBuilder_.mergeFrom(value);
        }
        structValueBuilder_.setMessage(value);
      }
      valueUnionCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * The entity value as an object. This object may be directly converted to a JSON representation.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 7;</code>
     */
    public Builder clearStructValue() {
      if (structValueBuilder_ == null) {
        if (valueUnionCase_ == 7) {
          valueUnionCase_ = 0;
          valueUnion_ = null;
          onChanged();
        }
      } else {
        if (valueUnionCase_ == 7) {
          valueUnionCase_ = 0;
          valueUnion_ = null;
        }
        structValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The entity value as an object. This object may be directly converted to a JSON representation.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 7;</code>
     */
    public com.google.protobuf.Struct.Builder getStructValueBuilder() {
      return getStructValueFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The entity value as an object. This object may be directly converted to a JSON representation.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 7;</code>
     */
    public com.google.protobuf.StructOrBuilder getStructValueOrBuilder() {
      if ((valueUnionCase_ == 7) && (structValueBuilder_ != null)) {
        return structValueBuilder_.getMessageOrBuilder();
      } else {
        if (valueUnionCase_ == 7) {
          return (com.google.protobuf.Struct) valueUnion_;
        }
        return com.google.protobuf.Struct.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The entity value as an object. This object may be directly converted to a JSON representation.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getStructValueFieldBuilder() {
      if (structValueBuilder_ == null) {
        if (!(valueUnionCase_ == 7)) {
          valueUnion_ = com.google.protobuf.Struct.getDefaultInstance();
        }
        structValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                (com.google.protobuf.Struct) valueUnion_,
                getParentForChildren(),
                isClean());
        valueUnion_ = null;
      }
      valueUnionCase_ = 7;
      onChanged();;
      return structValueBuilder_;
    }

    private java.lang.Object literal_ = "";
    /**
     * <pre>
     * The input literal associated with this entity.
     * </pre>
     *
     * <code>string literal = 8;</code>
     * @return The literal.
     */
    public java.lang.String getLiteral() {
      java.lang.Object ref = literal_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        literal_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The input literal associated with this entity.
     * </pre>
     *
     * <code>string literal = 8;</code>
     * @return The bytes for literal.
     */
    public com.google.protobuf.ByteString
        getLiteralBytes() {
      java.lang.Object ref = literal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        literal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The input literal associated with this entity.
     * </pre>
     *
     * <code>string literal = 8;</code>
     * @param value The literal to set.
     * @return This builder for chaining.
     */
    public Builder setLiteral(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      literal_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The input literal associated with this entity.
     * </pre>
     *
     * <code>string literal = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearLiteral() {
      
      literal_ = getDefaultInstance().getLiteral();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The input literal associated with this entity.
     * </pre>
     *
     * <code>string literal = 8;</code>
     * @param value The bytes for literal to set.
     * @return This builder for chaining.
     */
    public Builder setLiteralBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      literal_ = value;
      onChanged();
      return this;
    }

    private com.nuance.rpc.nlu.v1.AudioRange audioRange_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.AudioRange, com.nuance.rpc.nlu.v1.AudioRange.Builder, com.nuance.rpc.nlu.v1.AudioRangeOrBuilder> audioRangeBuilder_;
    /**
     * <pre>
     * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
     * </pre>
     *
     * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
     * @return Whether the audioRange field is set.
     */
    public boolean hasAudioRange() {
      return audioRangeBuilder_ != null || audioRange_ != null;
    }
    /**
     * <pre>
     * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
     * </pre>
     *
     * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
     * @return The audioRange.
     */
    public com.nuance.rpc.nlu.v1.AudioRange getAudioRange() {
      if (audioRangeBuilder_ == null) {
        return audioRange_ == null ? com.nuance.rpc.nlu.v1.AudioRange.getDefaultInstance() : audioRange_;
      } else {
        return audioRangeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
     * </pre>
     *
     * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
     */
    public Builder setAudioRange(com.nuance.rpc.nlu.v1.AudioRange value) {
      if (audioRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        audioRange_ = value;
        onChanged();
      } else {
        audioRangeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
     * </pre>
     *
     * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
     */
    public Builder setAudioRange(
        com.nuance.rpc.nlu.v1.AudioRange.Builder builderForValue) {
      if (audioRangeBuilder_ == null) {
        audioRange_ = builderForValue.build();
        onChanged();
      } else {
        audioRangeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
     * </pre>
     *
     * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
     */
    public Builder mergeAudioRange(com.nuance.rpc.nlu.v1.AudioRange value) {
      if (audioRangeBuilder_ == null) {
        if (audioRange_ != null) {
          audioRange_ =
            com.nuance.rpc.nlu.v1.AudioRange.newBuilder(audioRange_).mergeFrom(value).buildPartial();
        } else {
          audioRange_ = value;
        }
        onChanged();
      } else {
        audioRangeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
     * </pre>
     *
     * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
     */
    public Builder clearAudioRange() {
      if (audioRangeBuilder_ == null) {
        audioRange_ = null;
        onChanged();
      } else {
        audioRange_ = null;
        audioRangeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
     * </pre>
     *
     * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
     */
    public com.nuance.rpc.nlu.v1.AudioRange.Builder getAudioRangeBuilder() {
      
      onChanged();
      return getAudioRangeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
     * </pre>
     *
     * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
     */
    public com.nuance.rpc.nlu.v1.AudioRangeOrBuilder getAudioRangeOrBuilder() {
      if (audioRangeBuilder_ != null) {
        return audioRangeBuilder_.getMessageOrBuilder();
      } else {
        return audioRange_ == null ?
            com.nuance.rpc.nlu.v1.AudioRange.getDefaultInstance() : audioRange_;
      }
    }
    /**
     * <pre>
     * Range of audio input this operator applies to. Available only when interpreting a recognition result from ASR as a Service.
     * </pre>
     *
     * <code>.nuance.nlu.v1.AudioRange audio_range = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.nuance.rpc.nlu.v1.AudioRange, com.nuance.rpc.nlu.v1.AudioRange.Builder, com.nuance.rpc.nlu.v1.AudioRangeOrBuilder> 
        getAudioRangeFieldBuilder() {
      if (audioRangeBuilder_ == null) {
        audioRangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.nuance.rpc.nlu.v1.AudioRange, com.nuance.rpc.nlu.v1.AudioRange.Builder, com.nuance.rpc.nlu.v1.AudioRangeOrBuilder>(
                getAudioRange(),
                getParentForChildren(),
                isClean());
        audioRange_ = null;
      }
      return audioRangeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nuance.nlu.v1.SingleIntentEntity)
  }

  // @@protoc_insertion_point(class_scope:nuance.nlu.v1.SingleIntentEntity)
  private static final com.nuance.rpc.nlu.v1.SingleIntentEntity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nuance.rpc.nlu.v1.SingleIntentEntity();
  }

  public static com.nuance.rpc.nlu.v1.SingleIntentEntity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SingleIntentEntity>
      PARSER = new com.google.protobuf.AbstractParser<SingleIntentEntity>() {
    @java.lang.Override
    public SingleIntentEntity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SingleIntentEntity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SingleIntentEntity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SingleIntentEntity> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nuance.rpc.nlu.v1.SingleIntentEntity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

