// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: runtime.proto

package com.nuance.rpc.nlu.v1;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nuance.nlu.v1.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * HTTP status code. The 200 code means success, other values indicate an error.
   * </pre>
   *
   * <code>uint32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   * Brief description of the status.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Brief description of the status.
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Longer description if available.
   * </pre>
   *
   * <code>string details = 3;</code>
   * @return The details.
   */
  java.lang.String getDetails();
  /**
   * <pre>
   * Longer description if available.
   * </pre>
   *
   * <code>string details = 3;</code>
   * @return The bytes for details.
   */
  com.google.protobuf.ByteString
      getDetailsBytes();
}
